### ISSUE TITLE
Question: can I send Embedded Images via attachments?

### ISSUE THREAD

**Issue by ericfong** [RebelMail/nodemailer-mandrill-transport#18]
I am trying to do this
```
var mailOptions = {
    ...
    html: 'Embedded image: <img src="cid:unique@kreata.ee"/>',
    attachments: [{
        filename: 'image.png',
        path: '/path/to/file',
        cid: 'unique@kreata.ee' //same cid value as in the html img src
    }]
}
```

**Comment by motdotla** [comment]
This library does not support attachments at all at the moment @ericfong. It's something on the roadmap, but until then feel free to create a PR and we will review and merge in.

**Comment by motdotla** [comment]
Closing this. Provide a PR if you can. Otherwise, it will be something we get around to at a later time.

**Comment by ericfong** [comment]
Thx. I just need tags function and I found that the build-in SMTP can use headers to do the same thing. Sorry to move back to the built-in SMTP. 
BY the way, thanks for your works
