### ISSUE TITLE
incorrect bcc

### ISSUE THREAD

**Issue by david1983** [Rebelmail/nodemailer-mandrill-transport#28]
Hi,
I've noticed that at line 35 you concat the bcc addresses in the to instead of using the bcc_address option.
Using the "to" for bcc you lose the original recipient of the email and also it sends more emails and false your data stats on mandrill dashboard.

**Comment by elbuo8** [comment]
@devinus

**Comment by devinus** [comment]
Multiple BCC email addresses are appended to the `to` as type `bcc` (https://github.com/Rebelmail/nodemailer-mandrill-transport/blob/master/lib/mandrill-transport.js#L47) following the Mandrill API docs (https://mandrillapp.com/api/docs/messages.JSON.html#example-errorblock-send).

The `bcc_address` appears to only support one recipient. I'm not sure what kind of behavior you're expected.

**Comment by elbuo8** [comment]
@david1983 are you looking to use `bcc_address` or simply add several `bcc` recipients?

**Comment by jssuttles** [comment]
This behavior is not the behavior I expected from a bcc. If you send an email from Gmail with a bcc, the "to" recipient gets the email without being able to see the bcc. The "bcc" recipient gets the email and is also able to see the "to" recipient. What I get from this package is both the "bcc" and the "to" recipients get emails that have them as the "to" recipient even though one of them was "bcc"ed.
