### ISSUE TITLE
split 'from' into 'from_name' and 'from_address'

### ISSUE THREAD

**Issue by hsin421** [Rebelmail/nodemailer-mandrill-transport#34]
Right now I think I can only put 'from' in 'mailOptions' and there's a parser that splits the address into a name and an address.

Could we add 'from_name' manually?

If you'd like a PR I could do this and submit. 
Thanks

**Comment by devinus** [comment]
@hsin421 I'm not sure I understand the need for this? Just use `Kevin Bacon <kevin.bacon@gmail.com>` as the from and `from_name` will be `Kevin Bacon`.

**Comment by hsin421** [comment]
What if I use support@abc.com and want "from_name" to be ABC, the company?

**Comment by devinus** [comment]
@hsin421 `ABC <support@abc.com>`

**Comment by hsin421** [comment]
Ah thanks! I didn't quite know how email-addresses parser works.
